### ISSUE TITLE
bug: error handling in SSHNPParams / SSHNPPartialParams

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/noports#268]
### Describe the bug

SSHNPParams and SSHNPPartialParams are the only classes which exist outside of the main try block in the main for sshnp. They need to have their own internal error handling otherwise:

```
Unhandled exception:
PathNotFoundException: Cannot open file, path = 'playpen-sftp.env' (OS Error: No such file or directory, errno = 2)
#0      _File.throwIfError (dart:io/file_impl.dart:675)
#1      _File.openSync (dart:io/file_impl.dart:490)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:574)
#3      _File.readAsStringSync (dart:io/file_impl.dart:624)
#4      _File.readAsLinesSync (dart:io/file_impl.dart:630)
#5      SSHNPPartialParams._parseConfigFile (package:sshnoports/sshnp/sshnp_params.dart:239)
#6      new SSHNPPartialParams.fromConfig (package:sshnoports/sshnp/sshnp_params.dart:162)
#7      new SSHNPPartialParams.fromArgs (package:sshnoports/sshnp/sshnp_params.dart:177)
#8      main (file:///Users/chant/src/af/sshnoports/packages/sshnoports/bin/sshnp.dart:16)
#9      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:294)
#10     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189)
```

### Steps to reproduce

Try to pass a config file path which doesn't exist

### Expected behavior

A much nicer, cleaner error message

**Comment by xavierchanth** [comment]
I'd like to get this into v3.4.0 before we officially release. Hence P0.
I've fully completed this issue's estimates, left it in triage for visibility. Please move to active during planning.
