### ISSUE TITLE
Failed to fetch encryption public keys leads to failure in sshnoports server

### ISSUE THREAD

**Issue by sitaram-kalluri** [atsign-foundation/noports#27]
**Describe the bug**

Experiencing the below issue when starting sshnp server:

```
Unhandled exception:
Exception: Failed to fetch the current atSign public key - public:publickey@iot_manager
#0      AtClientImpl.get (package:at_client/src/client/at_client_impl.dart:255:7)
<asynchronous suspension>
#1      main (file:///C:/Users/colin/GitHub/@foundation/sshnoports/bin/sshnp.dart:207:26)
<asynchronous suspension>
```

**Additional context**
 This is inline with the conversation in engg. chat with threads group on Jul 29 2022.

**Comment by sitaram-kalluri** [comment]
The issue is fixed on upgrading to the latest at_onboarding_cli - v1.1.1
