### ISSUE TITLE
Username isn't being shared

### ISSUE THREAD

**Issue by JeremyTubongbanua** [atsign-foundation/noports#378]
### Describe the bug

Error on NPD (with `-u` flag):

```sh
Invalid argument(s): Unsupported block type for private key: 40
```

Error on NP: 

`
Request to remote secondary @server_0 at null:null received error response 'AT0015-Exception: @client_0:username.pi.sshnp@server_0 does not exist in keystore'
`

Without `-u` flag, the username is not shared with SSHNP at all.

I'm on completely fresh atSigns. Seems like the username isn't being shared at all. Everything seems to work with atSigns that have been used already.

### Steps to reproduce

1. Get fresh atSigns
2. Use installer scripts on device and client
3. Activate fresh atSigns
4. NPD does not share username with NP both with/without the `-u` flag

Video of me reproducing bug: https://drive.google.com/file/d/18CVH784O8ApR7EHJK7wekvlBkaMEKkmh/view?usp=sharing

### Expected behavior

SSHNPD should share username

### Additional context

Client : cannot find username
```sh
jeremytubongbanua@Jeremys-M2-Air:~|⇒  ~/.local/bin/sshnp -f @client_0 -t @server_0 -h @rv_am -s id_ed25519.pub -d pi -v
INFO|2023-08-22 21:23:09.278202|AtClientManager|setCurrentAtSign called with atSign @client_0 
INFO|2023-08-22 21:23:09.278308|AtClientManager|Switching atSigns from null to @client_0 
INFO|2023-08-22 21:23:09.280161|HiveBase|commit_log_d75a51c1003c996d4592b57407ea6b3f21a2e1163891d3612cb54a41aa363a01 initialized successfully 
INFO|2023-08-22 21:23:09.282211|HiveBase|d75a51c1003c996d4592b57407ea6b3f21a2e1163891d3612cb54a41aa363a01 initialized successfully 
INFO|2023-08-22 21:23:09.282267|AtClientCommitLogCompaction (@client_0)|Starting commit log compaction job running for every 11 minute(s) 
INFO|2023-08-22 21:23:09.283338|AtClientManager|setCurrentAtSign complete 
INFO|2023-08-22 21:23:09.283363|AtLookup|Creating new connection 
INFO|2023-08-22 21:23:09.733329|AtLookup|New connection created OK 
INFO|2023-08-22 21:23:09.857493|AtLookup|auth success 
INFO|2023-08-22 21:23:09.924078| sshnp |Subscribing to notifications on 7659907b-b980-41b6-92c1-fb0f92613cb6.pi.sshnp@ 
Device "pi" unknown, or username not shared 
INFO|2023-08-22 21:23:10.011159| sshnp |Tidying up files 
Exception: Internal server exception : Request to remote secondary @server_0 at null:null received error response 'AT0015-Exception: @client_0:username.pi.sshnp@server_0 does not exist in keystore'

Stack Trace: #0      AtClientImpl.get (package:at_client/src/client/at_client_impl.dart:349)
<asynchronous suspension>
#1      SSHNPImpl.fetchRemoteUserName (package:sshnoports/sshnp/sshnp_impl.dart:417)
<asynchronous suspension>
#2      SSHNPImpl.init (package:sshnoports/sshnp/sshnp_impl.dart:300)
<asynchronous suspension>
#3      main.<anonymous closure> (file:///Users/chant/src/af/sshnoports/packages/sshnoports/bin/sshnp.dart:57)
<asynchronous suspension>
#4      main (file:///Users/chant/src/af/sshnoports/packages/sshnoports/bin/sshnp.dart:37)
<asynchronous suspension>

INFO|2023-08-22 21:23:10.014539| sshnp |Tidying up files 
SEVERE|2023-08-22 21:23:10.014751| sshnp |Error deleting file : /Users/jeremytubongbanua/.ssh/7659907b-b980-41b6-92c1-fb0f92613cb6_sshnp 
SEVERE|2023-08-22 21:23:10.014918| sshnp |Error deleting file : /Users/jeremytubongbanua/.ssh/7659907b-b980-41b6-92c1-fb0f92613cb6_sshnp.pub 
```

Device without `-u` flag
```sh
pi@raspberrypi:~$ ~/.local/bin/sshnpd -a @server_0 -m @client_0 -d pi -s -v
INFO|2023-08-22 21:25:00.869725|AtClientManager|setCurrentAtSign called with atSign @server_0 
INFO|2023-08-22 21:25:00.870459|AtClientManager|Switching atSigns from null to @server_0 
INFO|2023-08-22 21:25:00.872453|HiveBase|commit_log_055719601711c762ce6bc501676e84468ea43ee6a20f32649e09e7cf951c9526 initialized successfully 
INFO|2023-08-22 21:25:00.874817|HiveBase|055719601711c762ce6bc501676e84468ea43ee6a20f32649e09e7cf951c9526 initialized successfully 
INFO|2023-08-22 21:25:00.878449|AtClientCommitLogCompaction (@server_0)|Starting commit log compaction job running for every 11 minute(s) 
INFO|2023-08-22 21:25:00.881053|AtClientManager|setCurrentAtSign complete 
INFO|2023-08-22 21:25:00.881336|AtLookup|Creating new connection 
INFO|2023-08-22 21:25:01.272930|AtLookup|New connection created OK 
INFO|2023-08-22 21:25:01.417230|AtLookup|auth success 
INFO|2023-08-22 21:25:01.426788| sshnpd |Starting heartbeat 
INFO|2023-08-22 21:25:01.426921| sshnpd |Subscribing to pi\.sshnp@ 
INFO|2023-08-22 21:25:01.427028| sshnpd |Done 
INFO|2023-08-22 21:25:01.660276|Monitor (@server_0)|monitor started for @server_0 with last notification time: null
```

Device: with `-u` flag
```sh
pi@raspberrypi:~$ ~/.local/bin/sshnpd -a @server_0 -m @client_0 -d pi -s -v -u
INFO|2023-08-22 21:22:57.459783|AtClientManager|setCurrentAtSign called with atSign @server_0 
INFO|2023-08-22 21:22:57.460694|AtClientManager|Switching atSigns from null to @server_0 
INFO|2023-08-22 21:22:57.466748|HiveBase|commit_log_055719601711c762ce6bc501676e84468ea43ee6a20f32649e09e7cf951c9526 initialized successfully 
INFO|2023-08-22 21:22:57.473543|HiveBase|055719601711c762ce6bc501676e84468ea43ee6a20f32649e09e7cf951c9526 initialized successfully 
INFO|2023-08-22 21:22:57.486559|AtClientCommitLogCompaction (@server_0)|Starting commit log compaction job running for every 11 minute(s) 
INFO|2023-08-22 21:22:57.489171|AtClientManager|setCurrentAtSign complete 
INFO|2023-08-22 21:22:57.489273|AtLookup|Creating new connection 
INFO|2023-08-22 21:22:57.841388|AtLookup|New connection created OK 
INFO|2023-08-22 21:22:57.963237|AtLookup|auth success 
Invalid argument(s): Unsupported block type for private key: 40
INFO|2023-08-22 21:22:58.187089| sshnpd |Starting heartbeat 
INFO|2023-08-22 21:22:58.187184| sshnpd |Subscribing to pi\.sshnp@ 
INFO|2023-08-22 21:22:58.187304| sshnpd |Updating device info for pi 
Invalid argument(s): Unsupported block type for private key: 40
INFO|2023-08-22 21:22:58.202610| sshnpd |Done 
INFO|2023-08-22 21:22:58.385370|Monitor (@server_0)|monitor started for @server_0 with last notification time: null 
```

Device SSHNPD (taken from e2e tests) of what it looks like with `-u` flag on old atSigns:

```sh
sshnpd  | 2023-08-22T23:39:53.207072436Z INFO|2023-08-22 23:39:53.206745|AtClientManager|setCurrentAtSign complete 
sshnpd  | 2023-08-22T23:39:53.207084936Z INFO|2023-08-22 23:39:53.206786|AtLookup|Creating new connection 
sshnpd  | 2023-08-22T23:39:53.773169588Z INFO|2023-08-22 23:39:53.773030|AtLookup|New connection created OK 
sshnpd  | 2023-08-22T23:39:53.866434118Z INFO|2023-08-22 23:39:53.866272|AtLookup|auth success 
sshnpd  | 2023-08-22T23:39:54.003924037Z INFO|2023-08-22 23:39:54.003783|AbstractAtKeyEncryption (@8052simple)|Encrypted shared symmetric key for @8052simple not found in local storage 
sshnpd  | 2023-08-22T23:39:54.003953337Z INFO|2023-08-22 23:39:54.003836|AbstractAtKeyEncryption (@8052simple)|Deleting @8incanteater:shared_key@8052simple from LocalSecondary 
sshnpd  | 2023-08-22T23:39:54.004702345Z INFO|2023-08-22 23:39:54.004629|AbstractAtKeyEncryption (@8052simple)|Fetching shared symmetric key for @8052simple from atServer 
sshnpd  | 2023-08-22T23:39:54.048379628Z INFO|2023-08-22 23:39:54.048251|AbstractAtKeyEncryption (@8052simple)|Retrieved my encrypted copy of shared symmetric key for @8incanteater from atServer - saving to local storage 
sshnpd  | 2023-08-22T23:39:54.054332093Z INFO|2023-08-22 23:39:54.054145|AbstractAtKeyEncryption (@8052simple)|'Their' copy of shared symmetric key for @8incanteater not found in local storage - will check atServer 
sshnpd  | 2023-08-22T23:39:54.098436680Z INFO|2023-08-22 23:39:54.098286|AbstractAtKeyEncryption (@8052simple)|Found 'their' copy of shared symmetric key for @8incanteater in atServer - saving to local storage 
sshnpd  | 2023-08-22T23:39:54.187452764Z INFO|2023-08-22 23:39:54.187300| sshnpd |Starting heartbeat 
sshnpd  | 2023-08-22T23:39:54.187481364Z INFO|2023-08-22 23:39:54.187355| sshnpd |Subscribing to 594505566020\.sshnp@ 
sshnpd  | 2023-08-22T23:39:54.188017970Z INFO|2023-08-22 23:39:54.187571| sshnpd |Updating device info for 594505566020 
sshnpd  | 2023-08-22T23:39:54.283478324Z INFO|2023-08-22 23:39:54.283329| sshnpd |Done 
sshnpd  | 2023-08-22T23:39:54.362544697Z INFO|2023-08-22 23:39:54.362342|Monitor (@8052simple)|monitor started for @8052simple with last notification time: null 
```

**Comment by JeremyTubongbanua** [comment]
Video of me reproducing bug (3 minutes): 
https://drive.google.com/file/d/18CVH784O8ApR7EHJK7wekvlBkaMEKkmh/view?usp=sharing

**Comment by xavierchanth** [comment]
This isn't a bug, it's intended to protect the devices in the event that a set of atKeys becomes exposed. In more security focused environments, they can setup their own SSH keys in addition to using SSHNP for obscurity, thus sshnpd is not responsible for sharing devicename or username. If -u is not supplied in sshnpd, then you must supply it in sshnp
