### ISSUE TITLE
ArgsParser `--list-devices` is an option instead of being a flag

### ISSUE THREAD

**Issue by JeremyTubongbanua** [atsign-foundation/noports#625]
I believe in v3, we had `--list-devices` as a flag as opposed to an option:

Now in v4.0.2 it's an option:

```sh
% ./sshnp -f @client_0 -t @server_0 -h @rv_eu --list-devices
Error: FormatException: Missing argument for "list-devices".

Stack Trace: #0      Parser._validate (package:args/src/parser.dart:311)
#1      Parser._readNextArgAsValue (package:args/src/parser.dart:123)
#2      Parser._handleLongOption (package:args/src/parser.dart:281)
#3      Parser._parseLongOption (package:args/src/parser.dart:264)
#4      Parser.parse (package:args/src/parser.dart:86)
#5      ArgParser.parse (package:args/src/arg_parser.dart:334)
#6      ExtendedArgParser.parse (package:sshnoports/src/extended_arg_parser.dart:38)
#7      main.<anonymous closure> (file:///Users/chant/src/af/sshnoports/packages/sshnoports/bin/sshnp.dart:43)
#8      _rootRun (dart:async/zone.dart:1399)
#9      _CustomZone.run (dart:async/zone.dart:1301)
#10     _runZoned (dart:async/zone.dart:1804)
#11     runZonedGuarded (dart:async/zone.dart:1792)
#12     main (file:///Users/chant/src/af/sshnoports/packages/sshnoports/bin/sshnp.dart:39)
#13     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295)
#14     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)
```

Attempting to do `--list-devices true` doesn't parse the String into a bool:
```sh
jeremytubongbanua@Jeremys-Air sshnp % ./sshnp -f @client_0 -t @server_0 -h @rv_eu --list-devices true
Error: type 'String' is not a subtype of type 'bool?'

Stack Trace: #0      new SshnpPartialParams.fromArgMap (package:noports_core/src/sshnp/models/sshnp_params.dart:340)
#1      new SshnpPartialParams.fromArgList (package:noports_core/src/sshnp/models/sshnp_params.dart:381)
#2      main.<anonymous closure> (file:///Users/chant/src/af/sshnoports/packages/sshnoports/bin/sshnp.dart:47)
#3      _rootRun (dart:async/zone.dart:1399)
#4      _CustomZone.run (dart:async/zone.dart:1301)
#5      _runZoned (dart:async/zone.dart:1804)
#6      runZonedGuarded (dart:async/zone.dart:1792)
#7      main (file:///Users/chant/src/af/sshnoports/packages/sshnoports/bin/sshnp.dart:39)
#8      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295)
#9      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)
```

Proof that I am on v4.0.2
```sh
jeremytubongbanua@Jeremys-Air sshnp % ./sshnp
Version : 4.0.2
    --[no-]help                      Print this usage information
-k, --key-file                       Sending atSign's atKeys file if not in ~/.atsign/keys/
-f, --from (mandatory)               Sending (a.k.a. client) atSign
-t, --to (mandatory)                 Receiving device atSign
-d, --device                         Receiving device name
                                     (defaults to "default")
...
Invalid argument(s): from is mandatory
```

**Comment by xavierchanth** [comment]
@JeremyTubongbanua I'll fix this by wednesday, but you can use an older version of 4.0.0 if you want to list devices immediately, that code has not changed just an issue with the arg parsing.

I know 4.0.0-rc.7 works well for this, just curl the release for it, and then copy the sshnp binary to ~/.local/bin/sshnp4rc7 (or some other name of your choosing)

Then you can do sshnp4rc7 -f ... -t ... --list-devices

**Comment by JeremyTubongbanua** [comment]
Thanks @XavierChanth
