### ISSUE TITLE
OpenWRT doesn't have `ssh-keygen`

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/noports#670]
### Describe the bug

When Python sshnpd tries to generate a key on OpenWRT it fails due to missing `ssh-keygen`

```
Generating SSH Keys
INFO:sshnpd:Generating SSH Keys
Exception in thread Thread-6 (sshnp_callback):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
  File "/usr/lib/python3.11/threading.py", line 982, in run
  File "/usr/lib/python3.11/site-packages/sshnpd.py", line 301, in sshnp_callback
  File "/usr/lib/python3.11/site-packages/sshnpd.py", line 263, in _direct_ssh
  File "/usr/lib/python3.11/site-packages/sshnpd.py", line 410, in _generate_ssh_keys
  File "/usr/lib/python3.11/subprocess.py", line 1026, in __init__
  File "/usr/lib/python3.11/subprocess.py", line 1950, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'ssh-keygen'
```
### Steps to reproduce

1. First I spin up a VM running OpenWRT 23.05.0 x86_64
2. Then I copy over the ipks from https://github.com/atsign-foundation/Atsign_OpenWRT_packages/releases/tag/v0.4.1
3. Ensure dependencies can be found with `opkg update`
4. Install SDK with `opkg install python3-atsdk_0.2.0-1_x86_64.ipk`
5. Install Python sshnpd with `opkg install python3-sshnpd_0.4.1-1_x86_64.ipk`
6. Copy over an atKey
7. Run sshnpd e.g. `sshnpd -m @cpswan -a @snowboard89 -d openwrt23 -u`
8. Attempt to connect from a client using sshnp

### Expected behavior

Daemon should test for presence of `ssh-keygen` before trying to run it, and provide an error message if it can't be found.

Alternatively use a pure Python way of generating keys.

### Additional context

I tripped over this as I tried to test Dropbear for #633

**Comment by XavierChanth** [comment]
We can do a dart native keygen, which is what we do for the pure-dart client

**Comment by xavierchanth** [comment]
@cpswan I'm going to wait to solve this in the C daemon.

**Comment by cpswan** [comment]
We can add `SELECTS:=openssh-keygen` to the Makefile, which I've done for the C sshnpd.
