### ISSUE TITLE
Ephemeral keys are written to ~/.sshnp which may not be present on a new machine. (Windows only)

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/noports#750]
### Describe the bug

~/.sshnp directory is not created now that we can run multiple sshnp's which means the directory is not available for ephemeral keys.
I think this bug is a hangover from the use of %TEMP% for the storage of atsign working files. ephemeral keys needs to be moved to that directory on Windows too.

This only seems to effect windows...

Workaound is to create the ~/.sshnp dir on windows

### Steps to reproduce

1. First install sshnp on a new machine (or delete ~/.sshnp) on Windows
2. Then try using sshnp
3. Error given 

### Expected behavior

No error message

### Screenshots

```
PS C:\sshnp> .\sshnp.exe -f "@cconstab" -t "@ssh_1" -d orac -u cconstab -i Z:\.ssh\GitHub_rsa -h "@rv_am" -k Z:\.atsign\keys\@cconstab_key.atKeys
2024-01-26 21:57:51.070493 : Resolving remote username for user session
2024-01-26 21:57:51.070493 : Resolving remote username for tunnel session
2024-01-26 21:57:51.070493 : Fetching host and port from srvd
2024-01-26 21:57:53.223884 : Sending session request to the device daemon
2024-01-26 21:57:54.053513 : Waiting for response from the device daemon
2024-01-26 21:57:54.849064 : Received response from the device daemon
2024-01-26 21:57:54.849064 : Creating connection to socket rendezvous

Error : PathNotFoundException: Cannot open file, path = 'C:\Users\cconstab\.sshnp\ephemeral_37b56bbb-7c53-4211-91dc-3e8ad501e6ce' (OS Error: The system cannot find the path specified.
, errno = 3)

Stack Trace: #0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381)
#2      _rootRunUnary (dart:async/zone.dart:1407)
<asynchronous suspension>
#3      _File.writeAsBytes.<anonymous closure> (dart:io/file_impl.dart:634)
<asynchronous suspension>
#4      ForwardingFile.writeAsString (package:file/src/forwarding/forwarding_file.dart:136)
<asynchronous suspension>
#5      Future.wait.<anonymous closure> (dart:async/future.dart:523)
<asynchronous suspension>
#6      LocalSshKeyUtil.addKeyPair (package:noports_core/src/common/at_ssh_key_util/local_ssh_key_util.dart:54)
<asynchronous suspension>
#7      SshnpOpensshLocalImpl.run (package:noports_core/src/sshnp/impl/sshnp_openssh_local_impl.dart:120)
<asynchronous suspension>
#8      main.<anonymous closure> (file:///d:/a/noports/noports/packages/dart/sshnoports/bin/sshnp.dart:160)
<asynchronous suspension>
#9      main (file:///d:/a/noports/noports/packages/dart/sshnoports/bin/sshnp.dart:82)
<asynchronous suspension>

PS C:\sshnp>
```

### Smartphones

- Windows

### Additional context

The task is easy but I was unsure of the best place to make the fix.. Would appreciate second pairt of eyes..

**Comment by gkc** [comment]
Working on this. Found some other bugs with ephemeral key management while doing so, fixing them too
